// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagazineApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MagazineEntry
    {
        /// <summary>
        /// Initializes a new instance of the MagazineEntry class.
        /// </summary>
        public MagazineEntry() { }

        /// <summary>
        /// Initializes a new instance of the MagazineEntry class.
        /// </summary>
        public MagazineEntry(int? id = default(int?), string name = default(string), int? count = default(int?), string localization = default(string))
        {
            Id = id;
            Name = name;
            Count = count;
            Localization = localization;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Localization")]
        public string Localization { get; set; }

    }
}
