// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagazineApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UnitsToSyncItem
    {
        /// <summary>
        /// Initializes a new instance of the UnitsToSyncItem class.
        /// </summary>
        public UnitsToSyncItem() { }

        /// <summary>
        /// Initializes a new instance of the UnitsToSyncItem class.
        /// </summary>
        public UnitsToSyncItem(int? id = default(int?), string name = default(string), string hostAndPort = default(string))
        {
            Id = id;
            Name = name;
            HostAndPort = hostAndPort;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hostAndPort")]
        public string HostAndPort { get; set; }

    }
}
