// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagazineWebService2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UnitEntry
    {
        /// <summary>
        /// Initializes a new instance of the UnitEntry class.
        /// </summary>
        public UnitEntry() { }

        /// <summary>
        /// Initializes a new instance of the UnitEntry class.
        /// </summary>
        public UnitEntry(int? id = default(int?), string name = default(string), int? count = default(int?), double? price = default(double?))
        {
            Id = id;
            Name = name;
            Count = count;
            Price = price;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double? Price { get; set; }

    }
}
